### ISSUE TITLE
Easily get a table of inparameters with value

### ISSUE THREAD

**Issue by rappen** [rappen/CustomActionTester#40]
Simplest JSON:
```json
{
    "new_Name": "Kalle",
    "new_Override": true
}
```
More complex JSON:
```json
{
    "params": [
        {
            "name": "new_Name",
            "type": "string",
            "value": "Kalle"
        },
        {
            "name": "new_Override",
            "type": "bool",
            "value": true
        },
        {
            "name": "new_Owner",
            "type": "EntityReference",
            "value": {
                "entityname": "systemuser",
                "id": "00000000-0000-0000-0000-000000000001"
            }
        }
    ]
}
```
YAML:
```yaml
parameters:
  - name: new_Name
    type: string
    value: Kalle
  - name: new_Overwrite
    type: bool
    value: True
  - name: new_Owner
    type: EntityReference
    value:
      entityname: systemuser
      id: 00000000-0000-0000-0000-000000000001
```

More types, thoughts, ideas?
